version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=node-mikro-orm-playground
    ports:
      - "5432:5432"
